In [1]:
import pandas as pd
import plotly.express as px

In [21]:
tf_idf_res = pd.read_excel('./log/tf-idf-ablation.xlsx', sheet_name=2)
# tf_idf_res = tf_idf_res[tf_idf_res['retrieval_threshold'] == 0]
tf_idf_res['trigger_rag'] = 103 - tf_idf_res['not_trigger_rag']

In [22]:
tf_idf_res

,Unnamed: 0,run_name,revise_count,rag_error,not_trigger_rag,total_accuracy,vector_store_name,n_min,n_max,max_features,min_df,max_df,use_idf,retrieval_threshold,retrieval_number,need_rerank,doc_final,model_type,vector_store type,trigger_rag
0,0,gemma-2b-it-prompt_eval-wiki_sg_exclusive_3_3_...,8,5,38,0.378641,wiki_sg_exclusive_3_3_None_1_0.1_True.pkl,3,3,NaN,1,0.100,True.pkl,0.01,2,False,8,gemma-2b-it,tf-idf,65
1,1,gemma-2b-it-prompt_eval-wiki_sg_exclusive_1_2_...,0,0,102,0.368932,wiki_sg_exclusive_1_2_None_1_0.01_True.pkl,1,2,NaN,1,0.010,True.pkl,0.30,4,False,8,gemma-2b-it,tf-idf,1
2,2,gemma-2b-it-prompt_eval-wiki_sg_exclusive_1_2_...,5,0,87,0.398058,wiki_sg_exclusive_1_2_None_1_0.001_True.pkl,1,2,NaN,1,0.001,True.pkl,0.15,4,False,8,gemma-2b-it,tf-idf,16
3,3,gemma-2b-it-prompt_eval-wiki_sg_exclusive_1_2_...,18,6,0,0.407767,wiki_sg_exclusive_1_2_None_1_0.01_True.pkl,1,2,NaN,1,0.010,True.pkl,0.10,4,False,8,gemma-2b-it,tf-idf,103
4,4,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,0,0,99,0.368932,wiki_sg_exclusive_2_2_None_1_0.1_True.pkl,2,2,NaN,1,0.100,True.pkl,0.20,4,False,8,gemma-2b-it,tf-idf,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,603,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,1,0.001,True.pkl,0.00,2,False,8,gemma-2b-it,tf-idf,103
604,604,gemma-2b-it-prompt_eval-wiki_sg_exclusive_1_1_...,17,7,0,0.388350,wiki_sg_exclusive_1_1_None_1_1.0_True.pkl,1,1,NaN,1,1.000,True.pkl,0.00,4,False,8,gemma-2b-it,tf-idf,103
605,605,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,0,0,102,0.368932,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,1,0.001,True.pkl,0.25,2,False,8,gemma-2b-it,tf-idf,1
606,606,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,0,0,99,0.368932,wiki_sg_exclusive_2_2_None_1_0.01_True.pkl,2,2,NaN,1,0.010,True.pkl,0.20,2,False,8,gemma-2b-it,tf-idf,4
607,607,gemma-2b-it-prompt_eval-wiki_sg_exclusive_1_1_...,18,6,1,0.398058,wiki_sg_exclusive_1_1_None_1_1.0_True.pkl,1,1,NaN,1,1.000,True.pkl,0.20,8,False,8,gemma-2b-it,tf-idf,102

In [23]:
# Define bins
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110]
labels = ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '90-100', '100+']

# Create a new column for the bins
tf_idf_res['trigger_rag_bins'] = pd.cut(tf_idf_res['trigger_rag'], bins=bins, labels=labels, right=False)

# Count the frequency of each bin
bin_counts = tf_idf_res['trigger_rag_bins'].value_counts()

# Create a pie chart
fig = px.pie(bin_counts, names=bin_counts.index, values=bin_counts, title='Distribution of Trigger RAG Number')

fig.update_layout(width=500, height=500)
# Show the plot
fig.show()

In [33]:
# Create a scatter plot
avg_trigger = tf_idf_res.groupby('retrieval_threshold')['trigger_rag'].mean().reset_index()
avg_trigger
fig = px.scatter(avg_trigger, x='retrieval_threshold', y='trigger_rag', title='Relationship between Trigger RAG and Retrieval Threshold')

# Show the plot
fig.update_layout(width=800, height=500)
fig.show()

In [35]:
tf_idf_res = tf_idf_res[tf_idf_res['trigger_rag'] >= 70]
len(tf_idf_res)

264

In [38]:
tf_idf_res.groupby(['n_min', 'n_max'])['total_accuracy'].max()

n_min  n_max
1      1        0.427184
       2        0.456311
       3        0.456311
2      2        0.485437
       3        0.466019
Name: total_accuracy, dtype: float64

In [39]:
tf_idf_res.groupby(['max_df'])['total_accuracy'].max()

max_df
0.001    0.485437
0.010    0.456311
0.100    0.456311
1.000    0.417476
Name: total_accuracy, dtype: float64

In [40]:
tf_idf_res.groupby(['retrieval_threshold'])['total_accuracy'].max()

retrieval_threshold
0.00    0.485437
0.01    0.485437
0.05    0.456311
0.10    0.456311
0.15    0.427184
0.20    0.417476
0.25    0.427184
0.30    0.388350
Name: total_accuracy, dtype: float64

In [42]:
tf_idf_res.groupby(['retrieval_number'])['total_accuracy'].max()

retrieval_number
1    0.485437
2    0.485437
4    0.485437
8    0.485437
Name: total_accuracy, dtype: float64

In [45]:
tf_idf_res.sort_values(by='total_accuracy', ascending=False).head(10)

,Unnamed: 0,run_name,revise_count,rag_error,not_trigger_rag,total_accuracy,vector_store_name,n_min,n_max,max_features,...,max_df,use_idf,retrieval_threshold,retrieval_number,need_rerank,doc_final,model_type,vector_store type,trigger_rag,trigger_rag_bins
319,319,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.01,8,False,8,gemma-2b-it,tf-idf,103,100+
9,9,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.00,4,False,8,gemma-2b-it,tf-idf,103,100+
603,603,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.00,2,False,8,gemma-2b-it,tf-idf,103,100+
455,455,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.01,2,False,8,gemma-2b-it,tf-idf,103,100+
452,452,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.01,4,False,8,gemma-2b-it,tf-idf,103,100+
263,263,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.00,1,False,8,gemma-2b-it,tf-idf,103,100+
278,278,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.00,8,False,8,gemma-2b-it,tf-idf,103,100+
99,99,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_2_...,23,5,0,0.485437,wiki_sg_exclusive_2_2_None_1_0.001_True.pkl,2,2,NaN,...,0.001,True.pkl,0.01,1,False,8,gemma-2b-it,tf-idf,103,100+
82,82,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_3_...,23,7,0,0.466019,wiki_sg_exclusive_2_3_None_1_0.001_True.pkl,2,3,NaN,...,0.001,True.pkl,0.01,4,False,8,gemma-2b-it,tf-idf,103,100+
463,463,gemma-2b-it-prompt_eval-wiki_sg_exclusive_2_3_...,23,7,0,0.466019,wiki_sg_exclusive_2_3_None_1_0.001_True.pkl,2,3,NaN,...,0.001,True.pkl,0.01,8,False,8,gemma-2b-it,tf-idf,103,100+

In [48]:
emb_res = pd.read_excel('./log/tf-idf-ablation.xlsx', sheet_name=1)
emb_res['trigger_rag'] = 103 - emb_res['not_trigger_rag']
emb_res = emb_res[emb_res['trigger_rag'] >= 70]

In [50]:
emb_res[emb_res['need_rerank'] == True]

,Unnamed: 0,run_name,revise_count,rag_error,not_trigger_rag,total_accuracy,vector_store_name,retrieval_threshold,retrieval_number,need_rerank,doc_final,model_type,meta_data,vector_store type,trigger_rag
6,6,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,23,9,17,0.446602,wiki_sg_exclusive_bge-large-en-v1.5,0.5,64,True,8,gemma-2b-it,{},embeddings,86
7,7,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.3,64,True,8,gemma-2b-it,{},embeddings,103
11,11,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.4,64,True,8,gemma-2b-it,{},embeddings,103
12,12,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.2,64,True,8,gemma-2b-it,{},embeddings,103

In [51]:
emb_res[emb_res['need_rerank'] == False]

,Unnamed: 0,run_name,revise_count,rag_error,not_trigger_rag,total_accuracy,vector_store_name,retrieval_threshold,retrieval_number,need_rerank,doc_final,model_type,meta_data,vector_store type,trigger_rag
8,8,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.2,6,False,8,gemma-2b-it,{},embeddings,103
9,9,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.4,6,False,8,gemma-2b-it,{},embeddings,103
10,10,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.3,6,False,8,gemma-2b-it,{},embeddings,103
13,13,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,25,12,0,0.427184,wiki_sg_exclusive_bge-large-en-v1.5,0.4,8,False,8,gemma-2b-it,{},embeddings,103
14,14,gemma-2b-it-prompt_eval-wiki_sg_exclusive_bge-...,23,9,17,0.446602,wiki_sg_exclusive_bge-large-en-v1.5,0.5,6,False,8,gemma-2b-it,{},embeddings,86